#---------------------------------#
#      environment configuration  #
#---------------------------------#
os: unstable
install:
  - cinst -y pester

#---------------------------------#
#      build configuration        #
#---------------------------------#
branches:
  only:
    - master

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

build: false
#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps: |
        $testResultsFile = ".\TestsResults.xml"
        $res = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru
        (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
        if ($res.FailedCount -gt 0) {
            throw "$($res.FailedCount) tests failed."
        }

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

# scripts to run before deployment
deploy_script:
  - ps: |
      irm 'https://raw.githubusercontent.com/smurawski/AppVeyorSampleHelper/master/TestHelper.psm1' | invoke-expression

      $Manifest = Get-ModuleManifestHash
      Update-ModuleManifest $Manifest
      $UpdatedManifest = Get-ModuleManifestHash
      $nupkg = New-ModuleNugetPackage $UpdatedManifest
      $zip = New-ModuleZipFile
      Publish-BuildArtifact -Path $nupkg, $zip
